version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '2g'
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: game_user
      POSTGRES_PASSWORD: game_password
      POSTGRES_DB: game_db
    ports:
      - '5432:5432'
